## BackPropagation Algo 
### 2 Layer

In [2]:
import numpy as np

Let's create all the function we going to need segmoid fct , derivation of seg. fct, and finalley the main function  

In [11]:

def g(x): 
    return 1/np.exp(-x)  # return the segmoid fct 

def dervG(x):
    return x*(1-x)     # calculate the derivation of  segmoid fct


def Back_prop2(X,y,numOut,numIter):
    #numInput is the number of  features
    y=y.T                   #  transpose 
    
  # random theta 
  # seed is optional  but for more deterministic   
    np.random.seed(1)
    theta=2*np.random.random((numOut,1))-1
    
    for i in range(numIter):
        a0=X
        #forward prop
        a1=g(np.dot(a0,theta))
        #error or the cost for layer 1
        a1_error=y-a1
        #print(l1_error[0])
        a1_delta=a1_error*dervG(a1)
        theta+=np.dot(a0.T,a1_delta)
    
    return theta
    
   


In [18]:
#number of column in X should be 

X = np.array([  [0,0,1,1],[0,1,1,1],[1,0,1,1],[1,1,1,1],[0,0,0,1] ])
   
y = np.array([[0,0,1,1,0]])

n,c=np.shape(X)

Back_prop2(X,y,c,2000)

array([[ 4.47571156e+00],
       [ 2.27438252e-04],
       [-3.71952499e-01],
       [-4.11529955e+00]])

In [106]:
def Back_prop3(x,y,numInput,layer,numIter):
    y=y.T
    np.random.seed(0)
    theta0=2*np.random.random((3,4))-1
    theta1=2*np.random.random((4,1))-1
    for i in range(numIter):
        a0=x
        a1=g(np.dot(a0,theta0))
        a2=g(np.dot(a1,theta1))
        a2_error=y-a2
        #print(a2_error[0])
        if (i% 100) == 0:
             print ("Error:" + str(np.mean(np.abs(a2_error))))
        a2_delta=a2_error*dervG(a2)
        
        a1_error=np.dot(a2_delta,theta1.T)
        a1_delta=a1_error*dervG(a1)
  
        theta0+=np.dot(a0.T,a1_delta)
        theta1+=np.dot(a1.T,a2_delta)
    return theta0,theta1


In [115]:
X = np.array([  [0,0,1],
                       [0,1,1],
                       [1,0,1],
                       [ 1,1,1],
                   ])
   
y = np.array([[0,0,1,0]])

n,c=np.shape(X)

Back_prop3(X,y,n,c,2000)

Error:0.3157818781833369
Error:0.2598877303831933
Error:0.25735709719910344
Error:0.256148112184051
Error:0.2553893540058043
Error:0.2548526609846387
Error:0.25444614007169
Error:0.2541241039946647
Error:0.2538607429577869
Error:0.25364015969089465
Error:0.2534519287802451
Error:0.2532888790955574
Error:0.25314588884795824
Error:0.253019186701759
Error:0.2529059247194165
Error:0.2528039060419468
Error:0.25271140494934635
Error:0.252627044320397
Error:0.25254970998936654
Error:0.25247848952509033


(array([[-0.12489951,  0.41340818,  1.42752042,  0.01137085],
        [-0.37410136,  0.36768011, -0.71576702,  0.36550039],
        [ 0.57077565, -0.24876382,  0.75729331, -0.32072601]]),
 array([[-1.10680126],
        [ 0.14853823],
        [-1.69175141],
        [-1.75456001]]))